import LocalizedStrings from "react-native-localization";
let Strings = new LocalizedStrings({
  en: {
    welcometoexadoctor: "Welcome to",
    prefered_language_title: "English",
    prefered_language: "Preferred Language",
    youhavesuccessfullylogout: "You have successfully logged out.",
    youhavesuccessfullylogin: "You have successfully logged in.",
    selectyoursiteurl: "Select your Exadoctor telehealth platform",
    entervalidsiteurl: "Select a valid Exadoctor telehealth platform.",
    siteurlisnotvalid:
      "The Exadoctor telehealth platform you have selected is not on production yet. Please contact Exadoctor customer support team at support@exadoctor.com.",
    configureappdetails:
      "Welcome to Exadoctor.com, your telehealth service for scheduling medical online appointment, videoconsultation, digital prescription, telemedicine and online payment.",
    menucleardata: "Clear App Data",
    pleaseupdateyourprofiledetails:
      "Please update your address and country details from profile screen.",
    registersuccessful:
      "Registered successfully. Verify your mobile OTP and Email. Activation link sent to your EmailId",
    accdoentexist:
      "Email or password incorrect. Please verify your credentials.",
    pwdsentsuccessfully:
      "Password changed successfully. Your new password has been sent to your email address.",
    pwderror: "Password could not be changed.",
    emailandmobilealreadyexist: "Email and mobile number already exist.",
    emailreadyexist: "Email and mobile number already exist.",
    mobilealreadyexist: "Mobile number is incorrect",
    otpsent: "OTP sent successfully",
    invalidotp: "Invalid OTP",
    emailverificationfailed:
      "Please validate your email address before login in. Check the email we sent you.",
    otpalreadyverified: "OTP is already verified",
    otpverified: "OTP verified successfully",
    dr: "Dr.",
    editprofile: "Edit Profile",
    nationalityinfo: "Nationality Info",
    approved: "Approved",
    present: "Present",
    consulting: "Consulting",
    closed: "Closed",
    close: "Close",
    noanswer: "No Answer",
    register: "Register",
    vertifyotp: "Verify OTP",
    myfavorites: "My Favorites",
    pleaseenteravalidintrx: "Please enter valid integer diagnosis value",
    userprofileupdated: "User profile has been updated",
    verifyotp: "Verify OTP",
    uploading: "Uploading..",
    practiceasindividual: "Practice as individual",
    upload: "Upload",
    resendotp: "Resend OTP",
    enterotp: "Enter OTP",
    verifyotplbl:
      "An SMS with a security code was sent to your mobile phone number",
    male: "Male",
    female: "Female",
    generalinfo: "General Info",
    firstname: "First Name",
    skipnow: "Skip Now",
    username: "User Name",
    lastname: "Last Name",
    gender: "Gender",
    overall: "Overall",
    patientstatus: "Patient Status",
    bedsidemanner: "Bedside Manner",
    waittime: "Wait Time",
    waittimemanner: "Wait Time Manner",
    selectgender: "Please select gender",
    mydoctors: "My Health Providers",
    doctors: "Health Providers",
    doctor: "Health Provider",
    doctorsname: "Type the name of the health provider",
    hospitalorclinic: "Hospital & Clinics",
    clinics: "Type the name of the health facility",
    fordoctors: "For Health Providers",
    forbranch: "For Branch",
    diagnostics: "Diagnostics",
    diagnosticcenter: "Diagnostic Centre",
    centername: "Center Name",
    removefavorite: "Remove Favourite",
    filter: "Filter",
    fromdate: "From Date",
    todate: "To Date",
    clearfilters: "Clear Filters",
    pleaseentervalidfirstname:
      "Please enter valid first name with only alphabets",
    pleaseentervalidlastname:
      "Please enter valid last name with only alphabets",
    pleaseentervalidtelephonenumber: "Please enter valid telephone number",
    pleaseentervalidsellingprice: "Please enter valid selling price",
    pleaseentervalidmanufacturerprice: "Please enter valid manufacturer price",
    pleaseentervalidboxsize: "Please enter valid box size",
    areyousureyouwanttoremovefavorite:
      "Are you sure you want to remove favorite?",
    areyousurewanttocleardata: "Are you sure want to clear data?",
    searchforlabs: "Search for Labs",
    professionalinfo: "Professional Info",
    choosespeciality: "Choose Specialty",
    ratingandreviews: "Ratings & Reviews",
    addanswer: "Add Answer",
    editanswer: "Edit Answer",
    videochat: "Video|Chat",
    online: "Videoconsultation",
    title: "Title",
    ok: "OK",
    q: "Q",
    appointments: "Appointments",
    appointmentid: "Appointment ID",
    scheduled: "Scheduled",
    pleasechoosewhentohave: "Please choose when to have the medicine",
    where: "Where",
    doctorname: "Health Provider Name",
    clinicname: "Health Facility Name",
    areyousureyouwanttocancelthisappointment:
      "Are you sure you want to cancel this appointment?",
    areyousureyouwanttodelete: "Are you sure you want to delete?",
    areyousureyouwanttoreschedule:
      "Are you sure you want to reschedule appointment?",
    practicename: "Practice Name",
    patientname: "Patient Name",
    enterpatientname: "Enter Patient Name",
    resonforvisit: "Reason for visit",
    bookinginstruction: "Booking Instruction",
    bookingdetails: "Appointment Details",
    whoisthisappointmentfor: "Who is this appointment for",
    haveyouseenthedoctorbefore: "Have you met the health provider before?",
    appointmenttype: "Appointment Type",
    additionalnotesfordoctor: "Additional notes for the health provider?",
    location: "Location",
    prescription: "Prescription",
    addprescription: "Log Consultation",
    organization: "Organization",
    certificationdate: "Certification date",
    allfieldsarerequired: "All fields are required",
    notyet: "Not yet",
    award: "Award",
    notes: "Notes",
    appointmentvia: "Type of appointment",
    experience: "Experience",
    awardsandrecognition: "Awards & Recognition",
    locationinfo: "Location Info",
    appointmentdate: "Appointment Date",
    me: "Me",
    someoneelse: "Someone else",
    iamanewpatient: "I am a new patient",
    iamexistingpatient: "I'm an existing patient",
    newpatient: "New Patient",
    existingpatient: "Already Seen",
    walking: "Walk-in",
    homecare: "Home Care",
    time: "Time",
    age: "Age",
    chooseimage: "Choose Image",
    uploadreport: "Upload Report",
    addreport: "Add Report",
    addnewmedicine: "Add New Medicine",
    editmedicine: "Edit Medicine",
    enterallmedicinedetails: "Enter all medicine details",
    diagnosticcenterinfo: "Diagnostic Center Info",
    diagnosticcenterfullname: "Diagnostic Center Full Name",
    pincode: "Pin Code",
    confirmpayment: "Confirm Your Payment",
    submit: "Submit",
    select: "Select",
    startdate: "Start Date",
    enddate: "End Date",
    selectdate: "select date",
    pleaseselectaslot: "Please select a slot",
    pleaseselect: "Please Select",
    save: "Save",
    mybranches: "My Branches",
    name: "Name",
    address: "Address",
    city: "City",
    state: "State",
    postalcode: "Postal Code",
    noslots: "No Slots",
    nodoctors: "No Health Providers",
    managelabtests: "Manage Lab Tests",
    searchresults: "Search Results",
    speciality: "Specialty",
    specialities: "Specialties",
    specialistdoctors: "Specialists",
    language: "Language",
    languages: "Languages",
    certifications: "Board Certifications",
    bloodgroup: "Blood Group",
    otherdetails: "Other Details(Optional)",
    country: "Country",
    choosecountry: "Choose Country",
    zipcode: "Zip Code",
    fax: "Fax",
    phone: "Phone",
    mobile: "Mobile",
    email: "Email",
    phonenumber: "Phone Number",
    password: "Password",
    confirmpassword: "Confirm Password",
    update: "Update",
    currentpassword: "Current Password",
    newpassword: "New Password",
    repassword: "Re-type New Password",
    birthdate: "Birth Date",
    emergencycontactname: "Emergency contact name",
    emergencycontactnumber: "Emergency contact number",
    personalinfo: "Personal Info",
    medicalinfo: "Medical Info",
    medicalrecords: "Medical Records",
    addmedicalrecord: "Add Medical Record",
    firstname: "First Name",
    enteryourfirstname: "Enter your first name",
    fminimumlength: "First Name must be minimum 3 characters",
    lminimumlength: "Last Name must be minimum 3 characters",
    lastname: "Last Name",
    enteryourlastname: "Enter your last name",
    aboutme: "About Me",
    boardcertification: "Board Certification",
    lbldob: "DOB",
    dob: "dob",
    enteryourdob: "Enter your dob",
    socialinfo: "Social Networks",
    website: "Website",
    enteryourwebsiteurl: "Enter your website url",
    facebookprofilelink: "Facebook profile link",
    twitterprofilelink: "Twitter profile link",
    googleplusprofilelink: "Google Plus profile link",
    linkedinprofilelink: "LinkedIn profile link",
    youtubeprofilelink: "Youtube profile link",
    accountdetails: "Account Details",
    enteraccountdetails: "Enter Account Details",
    amountaddedtowallet: "Amount added to wallet",
    profile: "Profile",
    all: "All",
    today: "Today",
    week: "Week",
    month: "Month",
    thisweek: "This Week",
    thismonth: "This Month",
    customdate: "Custom Date",
    description: "Description",
    created: "Created",
    credit: "Credit",
    debit: "Debit",
    edit: "Edit",
    next: "NEXT",
    day: "Day",
    hour: "Hour",
    book: "BOOK",
    continuepayment: "CONTINUE PAYMENT",
    setupyourlocation: "Set up your location",
    accept: "Accept",
    reject: "Reject",
    activities: "Activities",
    from: "From",
    to: "To",
    bookedon: "Booked On",
    gross: "Gross",
    myeducations: "My Educations",
    education: "Education",
    educations: "Educations",
    addeducation: "Add Education",
    editeducation: "Edit Education",
    paymentpending: "Payment Pending",
    pending: "Pending",
    waitingforacceptance: "Waiting For Acceptance",
    waitingforapproval: "Waiting For Approval",
    transactions: "Transactions",
    confirm: "Confirm",
    confirmed: "Confirmed",
    cancel: "Cancel",
    cancelled: "Cancelled",
    rejected: "Rejected",
    expired: "Expired",
    review: "Review",
    noreview: "No reviews added yet",
    dispute: "Dispute",
    attended: "Attended",
    waitingforreview: "Waiting for Review",
    waitingforbookerreview: "Waiting for Booker Review",
    waitingforpaymentcleared: "Waiting for Payment Cleared",
    completed: "Completed",
    enteryouremail: "Enter your email",
    entervalidemail: "Enter a valid email",
    enteryourpassword: "Enter your password",
    enterlogincredentials: "Enter your login credentials",
    minlenghtpwd: "Password should be minimum 6 characters",
    enternewpassword: "Enter new password",
    retypeyourpassword: "Re-type new password",
    minlenghtnpwd: "New Password should be minimum 6 characters",
    minlenghtcpwd: "Re-type Password should be minimum 6 characters",
    loginerror: "Please check your email and password",
    login: "Login",
    makebooking: "Make a Booking",
    createnewaccount: "Create new account",
    forgotpassword: "Forgot Password",
    changepassword: "Change Password",
    sociallogin: "SOCIAL LOGIN",
    loginwithfacebook: "Login with Facebook",
    loginwithtwitter: "Login with Twitter",
    loginwithgoogle: "Login with Google",
    enteryourusername: "Enter your username",
    confirmyourpassword: "Confirm your password",
    acceptterms: "By signing up you agree to our",
    passphrase:
      "Please enter the email address associated to your account, and we'll send you instructions.",
    addresspickmessage: "Please select a address",
    startdatemessage: "Pickup Date should be greater than current date & time",
    enddatemessage: "End Date Should be Greater than Start date & time",
    discount: "Discount",
    offer: "offer",
    nodata: "No data found",
    selectall: "Select All",
    loading: "Loading...",
    feedbacks: "Feedbacks",
    feedback: "Feedback",
    back: "Back",
    accessories: "Accessories",
    perrental: "per rental",
    insurance: "Insurance",
    insurances: "Insurances",
    other: "Other",
    referencecode: "Reference Code (optional)",
    taxes: "Taxes,",
    error: "Internal error has occured. Please check with log",
    checklogindetails: "Check your login credentials",
    passwordmismatch: "Password and Confirm password must be same",
    passwordrmismatch: "New Password and Re-type password must be same",
    minlengthusername: "Username should be minimum 3 characters",
    minlengthpassword:
      "Password and Confirm password should be minimum 6 characters",
    preferenceairconditioning: "Air Conditioning",
    preferencenonairconditioning: "Non - Air Conditioning",
    preferencemanualtransmission: "Manual Transmission",
    preferenceautotransmission: "Automatic Transmission",
    preferenceairbag: "Air Bag",
    entervalidurl: "Please check URLs are valid",
    enterhostname: "Enter host name of minimum 2 chars",
    entervalidmobilenumber: "Enter valid mobile number",
    entercurrentpassword: "Enter your current password",
    selectpickuplocation: "Select atlest one pickup location",
    selectdropuplocation: "Select atlest one dropup location",
    paynow: "Pay Now",
    confirmandpaynow: "Confirm & Pay Now",
    paylater: "Pay Later",
    iwillpaylater: "I will pay later >>",
    note: "Note",
    rating: "Rating",
    privatenote: "Private Note",
    areyousurewanttodelete: "Are you sure want to delete this from list?",
    maintenencestartdate: "Select valid start date",
    maintenenceenddate: "Select valid start date",
    enteraccountdetails: "Enter account details",
    reschedule: "Reschedule",
    search: "Search",
    nobookings: "No Bookings",
    addtowallet: "Add To Wallet",
    minwalletamount: "Minimum Wallet Amount: $10.00",
    maxwalletamount: "Maximum wallet amount: $1,000.00",
    minwwithdrawamount: "Minimum Withdrawal  GH¢2.00",
    maxwithdrawamount: "Maximum Withdrawal  GH¢1,000.00",
    minvalue: "Min: ",
    maxvalue: "Max: ",
    payerdetails: "PAYER DETAILS",
    creditcarddetails: "CREDIT CARD DETAILS",
    cardnumber: "Card Number",
    mm: "MM",
    yyyy: "YYYY",
    month: "Month",
    year: "Year",
    treatmentyear: "Treatment Year",
    nameoncard: "Name on card",
    cardcode: "Card Code",
    availablebalance: "Available Balance",
    entervalidamount: "Enter valid amount",
    checkavailablebalanceandentervalidamount:
      "Check available balance and enter valid amount",
    enteraddress: "Enter address",
    entercity: "Enter city",
    enterstate: "Enter state",
    enterzipcode: "Enter Zip code",
    entervalidphonenumber: "Enter valid phone number",
    entervalidcardnumber: "Enter valid card number",
    entervalidmonth: "Enter valid month",
    entervalidyear: "Enter valid year",
    enternameoncard: "Enter name on card",
    entervalidcardcode: "Enter valid card code",
    signuptermsofservice: "By signing up you agree to our",
    termsofservices: "Terms of Services",
    termsofservice:
      "By clicking the Pay Now button, you agree to our Terms of Services.",
    choosemoneytransferoption: "Choose your money transfer option",
    moneytransferaccount: "Money Transfer Account",
    amount: "Amount",
    date: "Date",
    account: "Account",
    status: "Status",
    appointmentstatus: "Appointment Status",
    appointmentnumber: "Appointment Token",
    cashwithdrawrequests: "Withdrawal Requests",
    view: "View",
    viewprofile: "View Profile",
    bookanappointment: "Book an Appointment",
    wallet: "Wallet",
    details: "Details",
    days: "Day(s)",
    hours: "Hour(s)",
    total: "Total",
    bookfor: "Book for",
    tax: "Tax",
    deposit: "Deposit",
    labtests: "Lab Tests",
    labreport: "Lab Report",
    labtestdetail: "Lab Test Detail",
    enterkeywordtosearch: "Keyword to search",
    invalidnumber: "Invalid Number",
    reasonforvisit: "Reason for visit",
    addlabtest: "Add Lab Test",
    editlabtest: "Edit Lab Test",
    onewaydropoffcharge: "One way drop off charge",
    droplocationdifferadditionalfee: "Drop Location Differ Additional Fee",
    surchargeamount: "Surcharge Amount",
    totalprice: "Total Price",
    typediscountamount: "Type Discount Amount",
    discount: "Discount",
    extraaccessoryamount: "Extra Accessory Amount",
    bookingplacessuccessfully: "Booking placed successfully",
    walletsuccess: "Your amount has been added to wallet successfully",
    cancelmessage: "Your have cancelled the payment",
    errormessage: "Request could not be processed. Try again later",
    unabletoprocess: "Unable to process your request. Please try again later.",
    walletmessage: "Your balance is not sufficient to pay",
    ordersuccess: "Your order payment has been completed successfully",
    enterprivatenote: "Enter private note",
    provideyourrating: "Select your rating star",
    checkin: "Check In",
    checkout: "Check Out",
    markasarrived: "Mark as Approved",
    startanappointment: "Start an Appointment",
    markasclosed: "Close Appointment",
    areyousureyouwanttochangestatus: "Are you sure you want to change status?",
    areyousurewanttocheckout: "Are you sure want to check out?",
    choosedisputetype: "Choose dispute type",
    disputemessage:
      "Current dispute for this booking hasn't been closed yet. Only one dispute at a time for an booking is possible.",
    cannotreview: "You cannot review when dispute is open",
    coupons: "Coupons",
    couponcode: "Coupon Code",
    entercouponcode: "Enter coupon code",
    apply: "Apply",
    orderamount: "Order Amount ",
    viewmore: "View more",
    viewless: "View less",
    viewreport: "View Report",
    askaquestion: "Ask a Question",
    myquestions: "My Questions",
    addquestion: "Add Question",
    editquestion: "Edit Question",
    pleaseenterpulse: "Please enter pulse",
    pleaseentertemperature: "Please enter temperature",
    pleaseenterdiagnosis: "Please enter diagnosis",
    signin: "Sign In",
    signup: "Sign up",
    donthaveaccText: "Don`t have an account?",

    logconsulation: "Log Consulation",
    patientcondition: "Patient Condition",
    condition: "Condition",
    weight: "Weight (Kg)",
    bp: "BP",
    pulse: "Pulse",
    temperature: "Temperature(C/F)",
    diagnosis: "Diagnosis",
    rx: "Rx#",
    medicine: "Medicine",
    medicinename: "Medicine Name",
    createprescription: "Create Prescription",
    addmedicine: "Add Medicine",
    test: "Test",
    addtest: "Add Test",
    advice: "Advice",
    addadvice: "Add Advice",
    beforefood: "Before Food",
    afterfood: "After Food",
    comments: "Comments",
    dose: "Dose",
    dosage: "Dosage",
    mgml: "Dose Regme",
    type: "Type",
    morning: "Morning",
    afternoon: "Afternoon",
    night: "Night",
    add: "Add",
    medicinelist: "Medicine Lists",
    medicines: "Medicines",
    nomedicinesadded: "No Medicines Added",
    notestsadded: "No Tests Added",
    noadvicesadded: "No Advices Added",
    testname: "Test Name",
    testdescription: "Test Description",
    pleaseenterecontactname: "Please enter emergency contact name",
    pleaseentervalidephonenumber: "Please enter valid emergency phone number",
    pleaseenterpatientcondition: "Please enter patient condition",
    pleaseenterbp: "Please enter BP",
    pleaseenteravalidweight: "Please enter a valid weight",
    pleaseenteravalidbp: "Please enter a valid BP",
    pleaseenteravalidrx: "Please enter a valid diagnosis",
    pleaseaddamedicine: "Please add a medicine",
    pleaseaddatest: "Please add a test",
    pleaseaddaadvice: "Please add a advice",
    pleasechooseamedicinetype: "Please choose a medicine type",
    pleaseenteramedicinename: "Please enter a medicine name",
    pleaseenteravalidmgml: "Please enter a valid mg/ml",
    pleaseenteravaliddose: "Please enter a valid dose",
    pleaseenteravaliddays: "Please enter a valid days",
    pleaseenteratestname: "Please enter a test name",
    pleaseenteraadvice: "Please enter a advice",
    usage: "Usage: ",
    notmentioned: "Not Mentioned",
    somethingwentwrong: "Something went wrong",
    pharmacyinfo: "Pharmacy Info",
    companyfullname: "Company Full Name",
    websiteurl: "Website URL",
    any: "Any",
    worknumber: "Work Number",
    homenumber: "Home Number",
    countrycode: "Country Code",
    contactinfo: "Contact Info",
    physiciantype: "Physician type",
    physicianlicensenumber: "Physician license number",
    primarytelepnonenumber: "Primary telephone number",
    primaryfaxnumber: "Primary fax number",
    pleaseselectphysiciantype: "Please select physician type",
    pleaseenterlicensenumber: "Please enter license number",
    pleaseenterprimarttelnumber: "Please enter primary telephone number",
    pleaseentervalidprimarttelnumber:
      "Please enter valid primary telephone number",
    pleaseentervalidfaxnumber: "Please enter valid fax number",
    consultationfee: "Consultation fee",
    addressandcontactinformation: "Address Info",
    area: "City",
    region: "Region-Department-County",
    otherdetail: "Other details",
    addressline2: "Address Line 2",
    addressline1: "Address Line 1",
    residentof: "Resident of",
    pleaseentercompanyname: "Please enter the name of the company",
    pleaseenteraddress: "Please enter an address",
    pleaseentercity: "Please enter a city",
    pleaseenterstate: "Please enter a state",
    id: "Id",
    unit: "Unit",
    name: "Name",
    sellprice: "Retail Price",
    mfprice: "Mf. Price",
    showmore: "Show More",
    manufacturer: "Manufacturer",
    category: "Category",
    boxsize: "Box Size",
    genericname: "Generic Name",
    pleaseenternameofthemedicine: "Please enter the name of the medicine",
    pleaseentergenericnameofthemedicine:
      "Please enter the generic name of the medicine",
    pleasechoosecategoryofthemedicine:
      "Please choose the category of the medicine",
    pleasechoosetypeofthemedicine: "Please choose the type of the medicine",
    pleasechoosetaxforthemedicine:
      "Please choose the tax value for the medicine",
    pleaseentersellingpriceofthemedicine:
      "Please enter the retail price of the medicine",
    pleaseentermanufacturerpriceofthemedicine:
      "Please enter the purchasing price of the medicine",
    pleasechoosetaxforthemedicine:
      "Please choose the tax value for the medicine",
    pleaseenterboxsizeofthemedicine:
      "Please enter the size of the box of the medicine",
    pleasechoosemanufacturerofthemedicine:
      "Please choose the manufacturer of the medicine",
    delivered: "Delivered?",
    appointmenttime: "Appointment Time",
    prescriptiondetails: "Prescription Details",
    sex: "Sex",
    id: "Id",
    dispatch: "Dispatch",
    quantity: "Quantity",
    price: "Price",
    payoption: "Please choose your money transfer pay option",
    proof: "Proof",
    verified: "Verified",
    getverified: "Get Verified",
    getverfiedheader: "Please verify your account",
    getverifieddesc:
      "Freelance health providers will have to upload their certifications, license, and IDs via the platform for manual verification before your account is activated.",
    doctorcertifications: "Health Provider Certifications",
    doctorcertdesc: "Please upload health provider certificate(s)",
    identityproof: "Identity Proof",
    identityproofdesc:
      "Please upload ONE ID type - Drivers License, National ID Card, Tax ID, Proof of Age Card, Professional License ID, State ID, Voter ID, Postal ID, Government-Issued Health Card and Other Government-Issued ID",
    addressproof: "Address Proof",
    addressproofdesc:
      "Please upload ONE document type - Utility Bill, Income Tax Return Form, Residence ID or Permit, Notarized Lease Agreement, ID Card (different to card used in proof of identity)",
    notyetsubmitted: "Not Yet Submitted",
    notsubmitted: "Not Submitted",
    pleaseselectanidtype: "Please select an ID type",
    pleaseselectadoctype: "Please select a document type",
    idtypes: "ID Proof Types",
    documenttypes: "Document Types",
    selectdoctorproof: "Select a health provider proof image",
    selectidproof: "Select an ID proof image",
    selectaddressproof: "Select address proof image",
    pleaseselectdate: "Please select a date",
    pleaseselectfromdate: "Please select from date",
    pleaseselecttodate: "Please select to date",
    deductedsitecommission: "Deducted site commission",
    youbookedanappointment: "You have booked an appointment.",
    bookedappointmentandamountinescrow:
      "booked appointment and amount in escrow.",
    appointmentcancelledandrefundedappointmentfee:
      "Appointment cancelled and refunded appointment fee.",
    appointmentcancelledandrefundedfromescrow:
      "Appointment cancelled and appointment fee refunded from escrow.",
    appointmentcompletedandfeecreditedtowallet:
      "Appointment completed and appointment fee credited to wallet.",
    paidfordiagnostictest: "Paid for Diagnostic test.",
    bookedfordiagnostictest: "Booked for Diagnostic test.",
    youpaidsubscriptionfee: "You have paid a subscription fee.",
    subscriptionplans: "Subscription",
    plan: "Plan",
    areyousurewanttocancelsubscription:
      "Are you sure you want to cancel this subscription?",
    yourequestedwithdrawamount:
      "You have requested to withdraw the available amount.",
    requestedamtcreditedtoaccanddebitfromwallet:
      "Requested withdraw amount credited to your account and debited from your available wallet amount.",
    withdrawrequestrejected:
      "Withdraw request rejected and amount credited back to your available wallet amount.",
    welcomeplansubscriptiontext:
      "You have a free membership subscription now. It will expire on: ######. After the plan expires, your profile will not be listed in searches unless you renew your subscription.",
    noplanssubscribed:
      "You have not subscribed for any plans. Your profile will not be listed in searches unless you renew your searches.",
    alreadysubscribed:
      "You have already subscribed ##PLAN## plan. You can renew your subscription once after the plan expires.",
    paymenterror: "Error in making payment. Try again after later.",
    areyousurewanttochangedeliveryoption:
      "Are you sure you want to change the delivery option?",
    paidviaonline: "Paid online?",
    yes: "Yes",
    no: "No",
    language_selection: "Language Selection",
    selectyourlanguage: "Select your language",
    hospitalorclinicname: "Health Facility Name",
    pleaseenterhospitalorclinicname:
      "Please enter the name of the health facility",
    hospitalorclinictype: "Speciality",
    pleaseselecthospitalorclinictype:
      "Please select the type of health facility",
    qanda: "Q&A",
    findyourperfect: "SEARCH FOR A HEALTH PROFESSIONAL",
    homelabel: "Health Provider . Hospital . Diagnostic Centre",
    homesublabel: "",
    menufindadoctor: "Find a Health Provider",
    menumyaccount: "My Account",
    menueditprofile: "Edit Profile",
    menulogin: "Login",
    menusubscription: "Subscription",
    menugetverified: "Get Verified",
    menumyappointment: "My Appointment",
    menumyeducation: "My Education",
    menumylanguage: "My Language",
    menumyspecialty: "My Specialty",
    menumyinsurance: "My Insurance",
    menumoneytransferaccount: "Money Transfer Account",
    menucashwithdrawls: "Cash Withdrawal",
    menutransactions: "Transactions",
    menumyfavorites: "My Favorites",
    menumylabtests: "My Lab Tests",
    menumedicalrecords: "Medical Records",
    menulabreports: "Lab Reports",
    menuaskaquestion: "Ask a Question",
    menumedicines: "Medicines",
    menumybranches: "My Branches",
    menulanguages: "Languages",
    menutermsandconditions: "Our Conditions",
    menuprivacypolicy: "Privacy Policy",
    menuchangepassword: "Change Password",
    menudeactivateaccount: "Deactivate my account",
    menulogout: "Logout",
    lblpatient: "Patient",
    lbldoctor: "Health Provider",
    currentlanguage: "en",
    prescriptionsupplylbl:
      "Do you want the prescription to be supplied by admin? Yes = Admin, No = Other",
    lblCountries: {
      Afghanistan: "Afghanistan",
      "Aland Islands": "Aland Islands",
      Albania: "Albania",
      Algeria: "Algeria",
      "American Samoa": "American Samoa",
      Andorra: "Andorra",
      Angola: "Angola",
      Anguilla: "Anguilla",
      Antarctica: "Antarctica",
      "Antigua and Barbuda": "Antigua and Barbuda",
      Argentina: "Argentina",
      Armenia: "Armenia",
      Aruba: "Aruba",
      Australia: "Australia",
      Austria: "Austria",
      Azerbaijan: "Azerbaijan",
      Bahamas: "Bahamas",
      Bahrain: "Bahrain",
      Bangladesh: "Bangladesh",
      Barbados: "Barbados",
      Belarus: "Belarus",
      Belgium: "Belgium",
      Belize: "Belize",
      Benin: "Benin",
      Bermuda: "Bermuda",
      Bhutan: "Bhutan",
      Bolivia: "Bolivia",
      Bonaire: "Bonaire",
      "Saint Eustatius and Saba": "Bonaire, Saint Eustatius and Saba",
      "Bosnia and Herzegovina": "Bosnia and Herzegovina",
      Botswana: "Botswana",
      "Bouvet Island": "Bouvet Island",
      Brazil: "Brazil",
      "British Indian Ocean Territory": "British Indian Ocean Territory",
      "British Virgin Islands": "British Virgin Islands",
      Brunei: "Brunei",
      Bulgaria: "Bulgaria",
      "Burkina Faso": "Burkina Faso",
      Burundi: "Burundi",
      Cambodia: "Cambodia",
      Cameroon: "Cameroon",
      Canada: "Canada",
      "Cape Verde": "Cape Verde",
      "Cayman Islands": "Cayman Islands",
      "Central African Republic": "Central African Republic",
      Chad: "Chad",
      Chile: "Chile",
      China: "China",
      "Christmas Island": "Christmas Island",
      "Cocos Islands": "Cocos Islands",
      Colombia: "Colombia",
      Comoros: "Comoros",
      "Cook Islands": "Cook Islands",
      "Costa Rica": "Costa Rica",
      Croatia: "Croatia",
      Cuba: "Cuba",
      Curacao: "Curacao",
      Cyprus: "Cyprus",
      "Czech Republic": "Czech Republic",
      "Democratic Republic of the Congo": "Democratic Republic of the Congo",
      Denmark: "Denmark",
      Djibouti: "Djibouti",
      Dominica: "Dominica",
      "Dominican Republic": "Dominican Republic",
      "East Timor": "East Timor",
      Ecuador: "Ecuador",
      Egypt: "Egypt",
      "El Salvador": "El Salvador",
      "Equatorial Guinea": "Equatorial Guinea",
      Eritrea: "Eritrea",
      Estonia: "Estonia",
      Ethiopia: "Ethiopia",
      "Falkland Islands": "Falkland Islands",
      "Faroe Islands": "Faroe Islands",
      Fiji: "Fiji",
      Finland: "Finland",
      France: "France",
      "French Guiana": "French Guiana",
      "French Polynesia": "French Polynesia",
      "French Southern Territories": "French Southern Territories",
      Gabon: "Gabon",
      Gambia: "Gambia",
      Georgia: "Georgia",
      Germany: "Germany",
      Ghana: "Ghana",
      Gibraltar: "Gibraltar",
      Greece: "Greece",
      Greenland: "Greenland",
      Grenada: "Grenada",
      Guadeloupe: "Guadeloupe",
      Guam: "Guam",
      Guatemala: "Guatemala",
      Guernsey: "Guernsey",
      Guinea: "Guinea",
      "Guinea-Bissau": "Guinea-Bissau",
      Guyana: "Guyana",
      Haiti: "Haiti",
      "Heard Island and McDonald Islands": "Heard Island and McDonald Islands",
      Honduras: "Honduras",
      "Hong Kong": "Hong Kong",
      Hungary: "Hungary",
      Iceland: "Iceland",
      India: "India",
      Indonesia: "Indonesia",
      Iran: "Iran",
      Iraq: "Iraq",
      Ireland: "Ireland",
      "Isle of Man": "Isle of Man",
      Israel: "Israel",
      Italy: "Italy",
      "Ivory Coast": "Ivory Coast",
      Jamaica: "Jamaica",
      Japan: "Japan",
      Jersey: "Jersey",
      Jordan: "Jordan",
      Kazakhstan: "Kazakhstan",
      Kenya: "Kenya",
      Kiribati: "Kiribati",
      Kosovo: "Kosovo",
      Kuwait: "Kuwait",
      Kyrgyzstan: "Kyrgyzstan",
      Laos: "Laos",
      Latvia: "Latvia",
      Lebanon: "Lebanon",
      Lesotho: "Lesotho",
      Liberia: "Liberia",
      Libya: "Libya",
      Liechtenstein: "Liechtenstein",
      Lithuania: "Lithuania",
      Luxembourg: "Luxembourg",
      Macao: "Macao",
      Macedonia: "Macedonia",
      Madagascar: "Madagascar",
      Malawi: "Malawi",
      Malaysia: "Malaysia",
      Maldives: "Maldives",
      Mali: "Mali",
      Malta: "Malta",
      "Marshall Islands": "Marshall Islands",
      Martinique: "Martinique",
      Mauritania: "Mauritania",
      Mauritius: "Mauritius",
      Mayotte: "Mayotte",
      Mexico: "Mexico",
      Micronesia: "Micronesia",
      Moldova: "Moldova",
      Monaco: "Monaco",
      Mongolia: "Mongolia",
      Montenegro: "Montenegro",
      Montserrat: "Montserrat",
      Morocco: "Morocco",
      Mozambique: "Mozambique",
      Myanmar: "Myanmar",
      Namibia: "Namibia",
      Nauru: "Nauru",
      Nepal: "Nepal",
      Netherlands: "Netherlands",
      "Netherlands Antilles": "Netherlands Antilles",
      "New Caledonia": "New Caledonia",
      "New Zealand": "New Zealand",
      Nicaragua: "Nicaragua",
      Niger: "Niger",
      Nigeria: "Nigeria",
      Niue: "Niue",
      "Norfolk Island": "Norfolk Island",
      "North Korea": "North Korea",
      "Northern Mariana Islands": "Northern Mariana Islands",
      Norway: "Norway",
      Oman: "Oman",
      Pakistan: "Pakistan",
      Palau: "Palau",
      "Palestinian Territory": "Palestinian Territory",
      Panama: "Panama",
      "Papua New Guinea": "Papua New Guinea",
      Paraguay: "Paraguay",
      Peru: "Peru",
      Philippines: "Philippines",
      Pitcairn: "Pitcairn",
      Poland: "Poland",
      Portugal: "Portugal",
      "Puerto Rico": "Puerto Rico",
      Qatar: "Qatar",
      "Republic of the Congo": "Republic of the Congo",
      Reunion: "Reunion",
      Romania: "Romania",
      Russia: "Russia",
      Rwanda: "Rwanda",
      "Saint Barthelemy": "Saint Barthelemy",
      "Saint Helena": "Saint Helena",
      "Saint Kitts and Nevis": "Saint Kitts and Nevis",
      "Saint Lucia": "Saint Lucia",
      "Saint Martin": "Saint Martin",
      "Saint Pierre and Miquelon": "Saint Pierre and Miquelon",
      "Saint Vincent and the Grenadines": "Saint Vincent and the Grenadines",
      Samoa: "Samoa",
      "San Marino": "San Marino",
      "Sao Tome and Principe": "Sao Tome and Principe",
      "Saudi Arabia": "Saudi Arabia",
      Senegal: "Senegal",
      Serbia: "Serbia",
      "Serbia and Montenegro": "Serbia and Montenegro",
      Seychelles: "Seychelles",
      "Sierra Leone": "Sierra Leone",
      Singapore: "Singapore",
      "Sint Maarten": "Sint Maarten",
      Slovakia: "Slovakia",
      Slovenia: "Slovenia",
      "Solomon Islands": "Solomon Islands",
      Somalia: "Somalia",
      "South Africa": "South Africa",
      "South Georgia and the South Sandwich Islands":
        "South Georgia and the South Sandwich Islands",
      "South Korea": "South Korea",
      "South Sudan": "South Sudan",
      Spain: "Spain",
      "Sri Lanka": "Sri Lanka",
      Sudan: "Sudan",
      Suriname: "Suriname",
      "Svalbard and Jan Mayen": "Svalbard and Jan Mayen",
      Swaziland: "Swaziland",
      Sweden: "Sweden",
      Switzerland: "Switzerland",
      Syria: "Syria",
      Taiwan: "Taiwan",
      Tajikistan: "Tajikistan",
      Tanzania: "Tanzania",
      Thailand: "Thailand",
      Togo: "Togo",
      Tokelau: "Tokelau",
      Tonga: "Tonga",
      "Trinidad and Tobago": "Trinidad and Tobago",
      Tunisia: "Tunisia",
      Turkey: "Turkey",
      Turkmenistan: "Turkmenistan",
      "Turks and Caicos Islands": "Turks and Caicos Islands",
      Tuvalu: "Tuvalu",
      "U.S. Virgin Islands": "U.S. Virgin Islands",
      Uganda: "Uganda",
      Ukraine: "Ukraine",
      "United Arab Emirates": "United Arab Emirates",
      "United Kingdom": "United Kingdom",
      "United States": "United States",
      "United States Minor Outlying Islands":
        "United States Minor Outlying Islands",
      Uruguay: "Uruguay",
      Uzbekistan: "Uzbekistan",
      Vanuatu: "Vanuatu",
      Vatican: "Vatican",
      Venezuela: "Venezuela",
      Vietnam: "Vietnam",
      "Wallis and Futuna": "Wallis and Futuna",
      "Western Sahara": "Western Sahara",
      Yemen: "Yemen",
      Zambia: "Zambia",
      Zimbabwe: "Zimbabwe",
    },
    weekdays: {
      0: "Sun",
      1: "Mon",
      2: "Tue",
      3: "Wed",
      4: "Thr",
      5: "Fri",
      6: "Sat",
    },
    lblappointmentstatus: {
      1: "Pending Approval",
      2: "Approved",
      3: "Closed",
      4: "Cancelled",
      5: "Rejected",
      6: "Expired",
      7: "Present",
      8: "Enquiry",
      9: "Pre-approved",
      10: "Payment Pending",
      11: "CanceledByAdmin",
    },
    lblinsurances: {
      1: "Acacia",
      2: "Nationwide",
      3: "Metropolitan",
      4: "Cosmopolitan",
      5: "Phoenix",
      6: "Universal",
      7: "Glico",
      8: "Premier",
    },
    lblspecialities: {
      1: "Allergologist",
      2: "Anesthesiologist",
      3: "Biologist",
      4: "Cardiologist",
      5: "Vascular Surgeon	",
      6: "Surgeon - Chirurgien",
      7: "Dentist",
      8: "Dermatologist",
      9: "Otolaryngologist",
      10: "Endocrinologist",
      11: "Eye Doctor",
      12: "Functional Reeducation",
      13: "Gastroenterologist",
      14: "General Practitioner",
      15: "Geriatrist",
      16: "Gynecologist-Obstetrician",
      18: "Hand Surgeon",
      19: "Internist",
      21: "Nephrologist",
      22: "Neurologist",
      23: "Psychiatrist",
      24: "Neurologue",
      25: "Neurosurgeon",
      26: "Nuclear Medicine",
      28: "Nurse",
      29: "Ophtalmologue",
      30: "Orthodontist",
      31: "Orthopedic Surgeon",
      32: "Osteopathe D.O.",
      33: "Pedopsychiatrist",
      34: "Pedriatician",
      35: "Physiotherapist",
      36: "Plastic Surgeon",
      37: "Psychiatrist",
      38: "Pulmonologist",
      39: "Radiologist",
      40: "Rheumatologist",
      41: "Sophrologist",
      42: "Sports Medicine Specialist",
      43: "Stomatologist",
      44: "Surgeon",
      45: "Urologist",
      46: "Vascular Surgeon",
      47: "Phlebologist",
      52: "Pharmacist",
      54: "Medical pedicure",
      55: "Podologist",
      56: "Psychologist",
      57: "Echographist",
      58: "Medical laboratory",
      60: "Personal trainer",
      61: "Fitnesscoach",
      62: "Pilates Trainer",
      63: "Foot massage",
      65: "IRM",
      66: "Scanner",
      68: "Consultation",
      69: "Acupuncture",
    },
    deactivateconfirmation: "Are you sure you want to deactivate your account?",
    deactivatesuccess: "Your Account is Deactivated Successfully",
    deactivatetryagain: "Something went wrong, please try again",
  },
  fr: {
    welcometoexadoctor: "Bienvenue sur",
    prefered_language_title: "Français",
    selectyoursiteurl: "Veuillez choisir votre plateforme de télésanté",
    youhavesuccessfullylogout: "Déconnexion effectuée.",
    youhavesuccessfullylogin: "Connexion acceptée.",
    entervalidsiteurl:
      "Veuillez choisir une plateforme de télésanté Exadoctor valide.",
    siteurlisnotvalid:
      "La plateforme de télésanté que vous avez choisie n'est pas actuellement en production. Pour plus d'information, veuillez contacter notre support technique à support@exadoctor.com .",
    configureappdetails:
      "Bienvenue sur Exadoctor, votre opérateur de télésanté multiservices: prise de rendez-vous médical en ligne, téléconsultation, prescription numérique, télésurveillance de patients atteints de diabète et parapharmacie.",
    menucleardata: "Effacer Données App",
    pleaseupdateyourprofiledetails: "Veuillez mettre à jour votre profil.",
    prefered_language: "Langue d'utilisation",
    registersuccessful:
      "Votre compte Exadoctor a été créé avec succès. Vous allez instantanément recevoir un courriel de confirmation, et un SMS contenant le code de vérification de votre mobile. Veuillez activer votre compte en suivant les instructions qui vous sont fournies dans le courriel.",
    accdoentexist:
      "Courriel ou mot de passe incorrect. Vérifiez vos identifiants.",
    pwdsentsuccessfully:
      "Votre mot de passe a été modifié. Vous allez recevoir un courriel contenant votre nouveau mot de passe.",
    pwderror: "Erreur: Le mot de passe n'a pas pu être modifié.",
    emailandmobilealreadyexist:
      "Erreur: un compte existe déjà avec l'adresse de courriel ou le numéro de téléphone fourni.",
    emailreadyexist: "Erreur: l'adresse de courriel est déjà utilisée.",
    mobilealreadyexist: "Erreur: le numéro de mobile est incorrect",
    otpsent:
      "Le code OTP de validation de votre numéro de mobile vous a été transmis.",
    invalidotp: "Erreur: Code OTP invalide.",
    otpalreadyverified: "Erreur: Le code OTP a déjà été vérifié.",
    emailverificationfailed:
      "Activez votre adresse de courriel avant de vous connecter. Consultez le courriel qui vous a été envoyé.",
    otpverified:
      "La validation OTP de votre numéro de mobile a été effectuée avec succès.",
    dr: "Dr ",
    selectyourlanguage: "Choisir votre langue",
    editprofile: "Editer votre profil",
    nationalityinfo: "Nationalité",
    approved: "Confirmé",
    present: "En cours",
    consulting: "En consultation",
    closed: "Fermé",
    close: "Fermer",
    noanswer: "Pas de réponse",
    register: "S'inscrire",
    vertifyotp: "Vérification OTP",
    myfavorites: "Mes favoris",
    pleaseenteravalidintrx: "Veuillez saisir un numéro de diagnostic valide",
    userprofileupdated: "Votre profil a été mis à jour.",
    verifyotp: "Vérification du code OTP",
    uploading: "Téléchargement..",
    practiceasindividual: "Exercer dans un cabinet médical",
    upload: "Télécharger",
    resendotp: "Renvoyer le code de vérification OTP de votre mobile",
    enterotp: "Saisir le code de vérification OTP de votre mobile",
    verifyotplbl:
      "Un SMS contenant le code de vérification OTP de votre mobile vous a été envoyé.",
    male: "Homme",
    female: "Femme",
    generalinfo: " Informations générales",
    firstname: " Prénoms",
    skipnow: "Ignorer",
    username: "  Nom",
    lastname: "Nom",
    gender: "Genre",
    overall: "Global",
    patientstatus: "Type de patient",
    bedsidemanner: "Au chevet du patient",
    waittime: "Temps d'attente",
    waittimemanner: "Temps d'attente",
    selectgender: "Sélectionner le genre",
    mydoctors: "Mes professionnels de santé",
    doctors: "Professionnels de santé",
    doctor: "Professionnel",
    doctorsname: "Entrez le nom du professionnel",
    hospitalorclinic: "Hôpital & Clinique",
    clinics: "Entrez le nom de l'établissement de santé",
    fordoctors: "Pour les professionnels de santé",
    forbranch: "Pour l'établissement",
    diagnostics: "Diagnostic",
    diagnosticcenter: "Centre de diagnostic",
    centername: "Nom du centre",
    removefavorite: "Supprimer le favori",
    filter: "Filtre",
    fromdate: "De",
    todate: "A",
    clearfilters: "Effacer les filtres",
    pleaseentervalidfirstname: "Saisir un prénom ne comportant que des lettres",
    pleaseentervalidlastname: "Saisir un nom ne comportant que des lettres",
    pleaseentervalidtelephonenumber: "Entrer un numéro de téléphone valide",
    pleaseentervalidsellingprice: "Saisir un prix de vente valide",
    pleaseentervalidmanufacturerprice: "Saisir un prix de fabricant valide",
    pleaseentervalidboxsize: "Saisir une taille de boîte valide",
    areyousureyouwanttoremovefavorite:
      "Voulez-vous vraiment supprimer le favori?",
    areyousurewanttocleardata: "Voulez-vous vraiment effacer les données?",
    searchforlabs: "Rechercher des laboratoires",
    professionalinfo: "Informations professionnelles",
    choosespeciality: "Choisissez un(e) spécialiste",
    ratingandreviews: "Évaluations et commentaires",
    addanswer: "Ajouter une réponse",
    editanswer: "Modifier la réponse",
    videochat: "Vidéo | Chat",
    online: "Vidéoconsultation",
    title: "Titre",
    ok: "O.K.",
    q: "Q",
    appointments: "RDVs",
    appointmentid: "Ref. de RDV",
    scheduled: "Planifié",
    pleasechoosewhentohave: "Choisir la date de prise du médicament",
    where: "Lieu",
    doctorname: "Nom du professionnel",
    clinicname: "Nom de l'établissement",
    areyousureyouwanttocancelthisappointment:
      "Voulez-vous vraiment annuler ce rendez-vous?",
    areyousureyouwanttodelete: "Etes-vous sûr de supprimer?",
    areyousureyouwanttoreschedule: "Voulez-vous replanifier le rendez-vous?",
    practicename: "Nom du cabinet",
    patientname: "Nom du patient",
    enterpatientname: "Entrer le nom du patient",
    resonforvisit: "Motif de consultation",
    bookinginstruction: "Instruction de prise de RDV",
    bookingdetails: "Détails de RDV",
    whoisthisappointmentfor: "Qui est le patient?",
    haveyouseenthedoctorbefore:
      "Avez-vous déjà été consulté par le professionnel de santé?",
    appointmenttype: "Type de RDV",
    additionalnotesfordoctor: "Notes",
    location: "Lieu",
    prescription: "Ordonnance",
    addprescription: "Ordonnance",
    organization: "Organisation",
    certificationdate: "Date de certification",
    allfieldsarerequired: "Tous les champs sont requis",
    notyet: "Pas encore",
    award: "Prix",
    notes: "Notes ",
    appointmentvia: "Type de RDV",
    experience: "Expérience",
    awardsandrecognition: "Prix ​​& Distinctions",
    locationinfo: "Lieu",
    appointmentdate: "Date de RDV",
    me: "Moi",
    someoneelse: "Un autre patient",
    iamanewpatient: "Nouveau patient",
    iamexistingpatient: "Patient déjà inscrit",
    newpatient: "Nouveau patient",
    existingpatient: "Patient déjà inscrit",
    walking: "Au cabinet",
    homecare: "A domicile",
    time: "Heure",
    age: "Âge",
    chooseimage: "Choisir image",
    uploadreport: "Téléchargement de rapport",
    addreport: "Ajout de rapport",
    addnewmedicine: "Ajout de médicament",
    editmedicine: "Modification de médicament",
    enterallmedicinedetails: "Détails de médicament",
    diagnosticcenterinfo: "Données centre de diagnostic",
    diagnosticcenterfullname: "Nom du centre de diagnostic",
    pincode: "Code PIN",
    confirmpayment: "Confirmer votre paiement",
    submit: "Transmettre",
    select: "Choisir",
    startdate: "Date de début",
    enddate: "Date de fin",
    selectdate: "Choix de date",
    pleaseselectaslot: "Veuillez choisir une plage horaire",
    pleaseselect: "Veuillez choisir",
    save: "sauvegarder",
    mybranches: "Mes établissements",
    name: "Nom",
    address: "Adresse",
    city: "Ville",
    state: "Région",
    postalcode: "Code postal",
    noslots: "Pas de plage horaire",
    nodoctors: "Pas de professionnel de santé",
    managelabtests: "Gestionn de tests de laboratoire",
    searchresults: "Résultats",
    speciality: "Spécialité",
    specialities: "Spécialités",
    specialistdoctors: "Spécialistes",
    language: "Langue",
    languages: "Langues",
    certifications: "Diplômes",
    bloodgroup: "Groupe sanguin",
    otherdetails: "Autres détails (facultatif)",
    country: "Pays",
    choosecountry: "Sélectionner un pays",
    zipcode: "Code postal",
    fax: "Fax",
    phone: "Téléphone",
    mobile: "Mobile",
    email: "Courriel",
    language_selection: "Langue",
    phonenumber: "Numéro de téléphone",
    password: "Mot de passe",
    confirmpassword: "Confirmation de mot de passe",
    update: "Mise à jour",
    currentpassword: "Mot de passe actuel",
    newpassword: "Nouveau mot de passe",
    repassword: "Veuillez re-taper votre nouveau mot de passe",
    birthdate: "Date de naissance",
    emergencycontactname: "Personne à joindre en urgence",
    emergencycontactnumber: "Numéro d'appel d'urgence",
    personalinfo: "Informations personnelles",
    medicalinfo: "Infos médicales",
    medicalrecords: "Dossiers médicaux",
    addmedicalrecord: "Ajouter un dossier médical",
    firstname: "Prénom",
    enteryourfirstname: "Entrer votre prénom",
    fminimumlength: "Le prénom doit contenir au moins 3 caractères",
    lminimumlength: "Le nom de famille doit comporter au moins 3 caractères",
    lastname: "Nom de famille",
    enteryourlastname: "Entrer votre nom de famille",
    aboutme: "Je me présente",
    boardcertification: "Diplômes",
    lbldob: "DDN",
    dob: "ddn",
    enteryourdob: "Entrez votre ddn",
    socialinfo: "Informations sociales",
    website: "Site web",
    enteryourwebsiteurl: "Entrer le nom de votre site Web",
    facebookprofilelink: "Profil Facebook",
    twitterprofilelink: "Profil Twitter",
    googleplusprofilelink: "Profil Google Plus",
    linkedinprofilelink: "Profil LinkedIn",
    youtubeprofilelink: "Profil Youtube",
    accountdetails: "Détails de compte",
    enteraccountdetails: "Entrer les détails de votre compte",
    amountaddedtowallet: "Montant ajouté au portefeuille",
    profile: "Profil",
    all: "Tous",
    today: " Aujourd'hui",
    week: "Semaine",
    month: "Mois",
    thisweek: "Cette semaine",
    thismonth: "Ce mois-ci",
    customdate: "Date personnalisée",
    description: "description",
    created: "Créé",
    credit: "Crédit",
    debit: "Débit",
    edit: "Éditer",
    next: "SUIVANT",
    day: "journée",
    hour: "Heure",
    book: "Prendre RDV",
    continuepayment: "CONTINUER",
    setupyourlocation: "Configurer votre localité",
    accept: "J'accepte",
    reject: "Rejeter",
    activities: "Activités",
    from: "De",
    to: "à",
    bookedon: "Date de prise de RDV:",
    gross: "Brut",
    myeducations: "Ma formation",
    education: "Formation",
    educations: "Formations",
    addeducation: "Ajouter une formation",
    editeducation: "Modifier la formation",
    paymentpending: "Paiement en attente",
    pending: "En attente",
    waitingforacceptance: " En attente d'acceptation",
    waitingforapproval: " En attente de confirmation",
    transactions: "Transactions",
    confirm: "Confirmer",
    confirmed: "Confirmé",
    cancel: "Annuler",
    cancelled: "Annulé",
    rejected: "Rejeté",
    expired: "Expiré",
    review: "Avis",
    noreview: "Pas d'avis dans l'immédiat",
    dispute: "Contestation",
    attended: "Présent",
    waitingforreview: " En attente d'avis",
    waitingforbookerreview: " En attente d'avis patient",
    waitingforpaymentcleared: "En attente d'encaissement de paiement",
    completed: "Terminé",
    enteryouremail: "Entrer votre courriel",
    entervalidemail: "Courriel invalide",
    enteryourpassword: "Saisir votre mot de passe",
    enterlogincredentials: "Entrez votre identifiant",
    minlenghtpwd: "Le mot de passe doit contenir au moins 6 caractères",
    enternewpassword: "Entrez un nouveau mot de passe",
    retypeyourpassword: "Re-saisir le nouveau mot de passe",
    minlenghtnpwd:
      "Le nouveau mot de passe doit contenir au moins 6 caractères",
    minlenghtcpwd:
      "Le nouveau mot de passe doit contenir au moins 6 caractères",
    loginerror: "Veuillez vérifier votre courriel et votre mot de passe",
    login: " S'identifier",
    makebooking: "Prendre RDV",
    createnewaccount: "Créer un nouveau compte",
    forgotpassword: "Mot de passe oublié",
    changepassword: "Changement de mot de passe",
    sociallogin: "CONNEXION RESEAUX SOCIAUX",
    loginwithfacebook: "Connexion Facebook",
    loginwithtwitter: "Connexion Twitter",
    loginwithgoogle: "Connexion Google",
    enteryourusername: " Veuillez entrer votre nom d'utilisateur",
    confirmyourpassword: "Veuillez confirmer votre mot de passe",
    acceptterms: "En vous inscrivant, vous acceptez nos",
    passphrase:
      " Veuillez saisir votre adresse de courriel et nous vous enverrons des instructions.",
    addresspickmessage: "Veuillez sélectionner une adresse",
    startdatemessage:
      " La date de prise en charge doit être supérieure à la date courante",
    enddatemessage:
      " La date de fin doit être supérieure à la date et à l'heure de début",
    discount: "Remise",
    offer: "offre",
    nodata: "Aucune donnée disponible",
    selectall: "Tout sélectionner",
    loading: "Chargement...",
    feedbacks: "Avis",
    feedback: " Avis",
    back: "Retour",
    accessories: "Accessoires",
    perrental: "par location",
    insurance: "Assurance",
    insurances: "Assurances",
    other: "Autre",
    referencecode: "Code de référence (facultatif)",
    taxes: "Taxes",
    error: " Une erreur interne s'est produite. Veuillez vérifier le journal.",
    checklogindetails: "Vérifier vos identifiants de connexion",
    passwordmismatch:
      "Le mot de passe et la confirmation du mot de passe doivent être identiques",
    passwordrmismatch:
      "Le mot de passe et la confirmation du mot de passe doivent être identiques",
    minlengthusername:
      " Le nom d'utilisateur doit contenir au moins 3 caractères",
    minlengthpassword:
      "Le mot de passe et la confirmation du mot de passe doivent contenir au moins 6 caractères",
    preferenceairconditioning: "Climatisation",
    preferencenonairconditioning: "Pas de climatisation",
    preferencemanualtransmission: "Transmission manuelle",
    preferenceautotransmission: "Transmission automatique",
    preferenceairbag: "Air Bag",
    entervalidurl:
      "Veuillez vérifier que les adresses des sites web sont valides",
    enterhostname: " Entrez au minimum 2 caractères pour le nom d'hôte",
    entervalidmobilenumber: "Entrez un numéro de mobile valide",
    entercurrentpassword: "Entrer votre mot de passe actuel",
    selectpickuplocation: "Sélectionnez au moins un lieu de collecte",
    selectdropuplocation: "Sélectionnez au moins un lieu de dépôt",
    paynow: "Payer",
    confirmandpaynow: "Paiement en ligne",
    paylater: "Paiement différé",
    iwillpaylater: "Je paierai plus tard >>",
    note: "Remarque",
    rating: "Évaluation",
    privatenote: "Note personnelle",
    areyousurewanttodelete: "Voulez-vous vraiment supprimer cela de la liste?",
    maintenencestartdate: "Choisir une date de début valide",
    maintenenceenddate: "Choisir une date de début valide",
    enteraccountdetails: "Entrez les détails du compte",
    reschedule: "Reprogrammer",
    search: "Chercher",
    nobookings: "Aucun RDV",
    addtowallet: "Ajouter au portefeuille",
    minwalletamount: "Montant minimum du portefeuille: 10,00 $",
    maxwalletamount: "Montant maximum du portefeuille: 1000,00 $",
    minwwithdrawamount: "Retrait minimal 2,00",
    maxwithdrawamount: "Retrait maximal 1000,00",
    minvalue: "Min:",
    maxvalue: "Max:",
    payerdetails: "DÉTAILS DU PAYEUR",
    creditcarddetails: "DÉTAILS DE LA CARTE DE CRÉDIT",
    cardnumber: "Numéro de carte",
    mm: "MM",
    yyyy: "aaaa",
    month: "Mois",
    year: "Année",
    treatmentyear: "Année de traitement",
    nameoncard: "Nom figurant sur la carte",
    cardcode: "Code de la carte",
    availablebalance: "Solde disponible",
    entervalidamount: "Entrez un montant valide",
    checkavailablebalanceandentervalidamount:
      "Vérifier le solde disponible et entrer un montant valide",
    enteraddress: "Saisir une adresse",
    entercity: "Saisir une ville",
    enterstate: "Saisir la région",
    enterzipcode: "Entrer un code postal",
    entervalidphonenumber: "Entrez un numéro de téléphone valide",
    entervalidcardnumber: "Entrez un numéro de carte valide",
    entervalidmonth: "Entrez un mois valide",
    entervalidyear: "Entrez une année valide",
    enternameoncard: "Entrez le nom sur la carte",
    entervalidcardcode: "Entrez un code de carte valide",
    signuptermsofservice: "En vous inscrivant, vous acceptez nos",
    termsofservices: "Termes et Conditions",
    termsofservice:
      " En cliquant sur payer, vous acceptez nos conditions générales d'utilisation.",
    choosemoneytransferoption: " Choisissez votre option de transfert d'argent",
    moneytransferaccount: "Compte de transfert d'argent",
    amount: "Montant",
    date: "Date",
    account: "Compte",
    status: "Statut",
    appointmentstatus: "Statut du RDV",
    appointmentnumber: "Référence",
    cashwithdrawrequests: "Demandes de retrait",
    view: "Afficher",
    viewprofile: "Profil",
    bookanappointment: "Prendre un RDV",
    wallet: "Portefeuille",
    details: "Détails",
    days: "Jour(s)",
    hours: "Heures",
    total: "Total",
    bookfor: "RDV pris pour",
    tax: "Taxe",
    deposit: "Acompte",
    labtests: "Tests de laboratoire",
    labreport: "Rapport de laboratoire",
    labtestdetail: "Détails de test de laboratoire",
    enterkeywordtosearch: "Mot-clé de recherche",
    invalidnumber: "Numéro invalide",
    reasonforvisit: "Motif de visite",
    addlabtest: "Ajouter un test de laboratoire",
    editlabtest: "Modifier le test de laboratoire",
    onewaydropoffcharge: "Frais de livraison",
    droplocationdifferadditionalfee:
      "Frais additionnels si lieu de livraison différent ",
    surchargeamount: "Montant du supplément",
    totalprice: "Prix ​​total",
    typediscountamount: "Type de remise",
    discount: "Remise",
    extraaccessoryamount: "Frais supplémentaires",
    bookingplacessuccessfully: "Prise de RDV effectuée avec succès",
    walletsuccess: "Votre montant a bien été ajouté au portefeuille",
    cancelmessage: "Vous avez annulé le paiement",
    errormessage: " La demande n'a pas pu être traitée. Réessayez plus tard",
    unabletoprocess:
      "Impossible de traiter votre demande. Veuillez réessayer plus tard.",
    walletmessage: " Votre solde n'est pas suffisant pour payer",
    ordersuccess: "Le règlement de votre commande a été effectué avec succès",
    enterprivatenote: "Saisir une information personnelle",
    provideyourrating: " Sélectionnez votre notre d'évaluation",
    checkin: "Enregistrement",
    checkout: "Départ",
    markasarrived: "Mark as Approved",
    startanappointment: "Débuter Consultation",
    markasclosed: "Clôturer Consultation",
    areyousureyouwanttochangestatus: "Voulez-vous vraiment changer le statut?",
    areyousurewanttocheckout: '"Voulez-vous vraiment quitter?"',
    choosedisputetype: "Choisissez le type de litige",
    disputemessage:
      "Un litige relatif à ce RDV est toujours en cours. Il ne put y avoir qu'un litige par RDV.",
    cannotreview:
      "Une évaluation ne peut être effecuée lorsqu'un lorsqu'un litige est ouvert.",
    coupons: "Coupons",
    couponcode: "Code promo",
    entercouponcode: "Entrer le code de réduction",
    apply: "Valider",
    orderamount: "Montant de la commande",
    viewmore: "Afficher plus",
    viewless: "Afficher moins",
    viewreport: "Voir le rapport",
    askaquestion: "Poser une question",
    myquestions: "Mes questions",
    addquestion: "Ajouter une question",
    editquestion: "Modifier la question",
    pleaseenterpulse: "Veuillez saisir le pouls",
    pleaseentertemperature: "Veuillez entrer la température",
    pleaseenterdiagnosis: "Veuillez saisir le diagnostic",
    signin: "Se connecter",
    signup: " S'inscrire",
    donthaveaccText: " Vous n'avez pas de compte?",
    logconsulation: "Prescrire une ordonnance",
    patientcondition: "État du patient",
    condition: "État",
    weight: "Poids (kg)",
    bp: "Pression artérielle PA",
    pulse: "Impulsion",
    temperature: "Température (C/F)",
    diagnosis: "Diagnostic",
    rx: "Rx #",
    medicine: "Médicament",
    medicinename: "Nom du médicament",
    createprescription: "Prescrire une ordonnance",
    addmedicine: "Ajouter un médicament",
    test: "Tester",
    addtest: "Ajouter un test",
    advice: "Conseil",
    addadvice: "Ajouter notes de conseil",
    beforefood: "Avant un repas",
    afterfood: "Après un repas",
    comments: "Commentaires",
    dose: "Dose",
    dosage: "Dosage",
    mgml: "mg-ml",
    type: "Type",
    morning: "Matin",
    afternoon: "Après-midi",
    night: "Nuit",
    add: "Ajouter",
    medicinelist: "Liste de médicaments",
    medicines: "Médicaments",
    nomedicinesadded: "Pas d'ajout de médicaments",
    notestsadded: "Pas d'ajout de tests",
    noadvicesadded: "Aucun avis ajouté",
    testname: "Nom du test",
    testdescription: "Description du test",
    pleaseenterecontactname: "Personne à contacter en urgence",
    pleaseentervalidephonenumber: "N°de téléphone à contacter en urgence",
    pleaseenterpatientcondition: " Veuillez saisir l'état du patient",
    pleaseenterbp: "Veuillez saisir la pression artérielle PA",
    pleaseenteravalidweight: "Veuillez saisir un poids valide",
    pleaseenteravalidbp: "Veuillez saisir une pression artériell PA valide",
    pleaseenteravalidrx: "Veuillez saisir un diagnostic valide",
    pleaseaddamedicine: "Veuillez ajouter un médicament",
    pleaseaddatest: "Veuillez ajouter un test",
    pleaseaddaadvice: "Veuillez ajouter un avis",
    pleasechooseamedicinetype: "Veuillez choisir un type de médicament",
    pleaseenteramedicinename: "Veuillez saisir un nom de médicament",
    pleaseenteravalidmgml: "Veuillez entrer une valeur en  mg ou ml",
    pleaseenteravaliddose: "Veuillez entrer une dose valide",
    pleaseenteravaliddays: "Veuillez saisir des jours valides",
    pleaseenteratestname: "Veuillez saisir un nom de test",
    pleaseenteraadvice: "Veuillez écrire un avis",
    usage: "Usage:",
    notmentioned: "Pas mentionné",
    somethingwentwrong: " Une erreur s'est produite",
    pharmacyinfo: "Info pharmacie",
    companyfullname: " Nom de l'entreprise",
    websiteurl: "Adresse du site web",
    any: "H ou F",
    worknumber: "Numéro de travail",
    homenumber: "Numéro de domicile",
    countrycode: "Code postal",
    contactinfo: "Informations de contact",
    physiciantype: "Type de médecin",
    physicianlicensenumber: "Numéro de licence",
    primarytelepnonenumber: "Numéro de téléphone principal",
    primaryfaxnumber: "Numéro de fax principal",
    pleaseselectphysiciantype: "Sélectionner le type de professionnel de santé",
    pleaseenterlicensenumber: "Veuillez entrer votre numéro de licence",
    pleaseenterprimarttelnumber:
      "Veuillez entrer un numéro de téléphone principal",
    pleaseentervalidprimarttelnumber:
      "Veuillez entrer un numéro de téléphone principal",
    pleaseentervalidfaxnumber: "Veuillez entrer un numéro de fax",
    consultationfee: "Frais de consultation",
    addressandcontactinformation: " Informations adresse et contact",
    area: "Ville",
    region: "Région-Département",
    otherdetail: "Autres détails",
    addressline2: "Adresse 2",
    addressline1: "Adresse 1",
    residentof: "Résident de",
    pleaseentercompanyname: " Veuillez saisir le nom de l'entreprise",
    pleaseenteraddress: " Veuillez saisir l'adresse",
    pleaseentercity: "Veuillez entrer la ville",
    pleaseenterstate: " Veuillez entrer la région",
    id: "Id",
    unit: "Unité",
    name: "Nom",
    sellprice: "Prix ​​de vente",
    mfprice: "Mf. Prix",
    showmore: "Afficher plus",
    manufacturer: "Fabricant",
    category: "Catégorie",
    boxsize: "Taille de boîte",
    genericname: "Nom générique",
    pleaseenternameofthemedicine: "Veuillez saisir le nom du médicament",
    pleaseentergenericnameofthemedicine:
      "Veuillez saisir le nom générique du médicament",
    pleasechoosecategoryofthemedicine:
      "Veuillez choisir la catégorie du médicament",
    pleasechoosetypeofthemedicine: "Veuillez choisir le type de médicament",
    pleasechoosetaxforthemedicine:
      "Veuillez choisir la taxe pour le médicament",
    pleaseentersellingpriceofthemedicine:
      "Veuillez saisir le prix de vente du médicament",
    pleaseentermanufacturerpriceofthemedicine:
      "Veuillez saisir le prix du fabricant du médicament",
    pleasechoosetaxforthemedicine:
      "Veuillez choisir la taxe pour le médicament",
    pleaseenterboxsizeofthemedicine:
      "Veuillez saisir la taille de la boîte du médicament",
    pleasechoosemanufacturerofthemedicine:
      "Veuillez choisir le fabricant du médicament",
    delivered: "Livré",
    appointmenttime: "Heure de RDV",
    prescriptiondetails: "Détails de prescription",
    sex: "Genre",
    id: "Id",
    dispatch: "Envoi",
    quantity: "Quantité",
    price: "Prix",
    payoption:
      "Veuillez choisir votre option de paiement de transfert d'argent",
    proof: "Preuve",
    verified: "Vérifié",
    getverified: "Autorisation d'Exercice",
    getverfiedheader: "Vérification",
    getverifieddesc:
      "Les professionnels de santé indépendants devront télécharger leur licence et leurs identifiants via la plateforme pour une vérification manuelle avant l'activation de leur compte.",
    doctorcertifications: "Diplômes professionnels",
    doctorcertdesc:
      "Veuillez télécharger le permis d'exercice du professionnel de santé",
    identityproof: "Pièces d'identité",
    identityproofdesc:
      "Veuillez télécharger un type d'ID: Permis de conduire, Carte d'identité nationale, Passeport",
    addressproof: "Justificatifs d'Etablissement Professionnel",
    addressproofdesc:
      "Veuillez télécharger un document de type formulaire de déclaration de revenus, factures de services publics, contrat de location notarié",
    notyetsubmitted: "Pas encore transmis",
    notsubmitted: "Pas transmis",
    pleaseselectanidtype: "Veuillez sélectionner une pièce d'identité",
    pleaseselectadoctype: "Veuillez sélectionner un type de document",
    idtypes: "Types de pièces d'identité",
    documenttypes: "Types de documents",
    selectdoctorproof: "Choisir la photo du médecin",
    selectidproof: " Sélectionnez une image",
    selectaddressproof: "Sélectionnez la preuve d'adresse",
    pleaseselectdate: "Veuillez sélectionner la date",
    pleaseselectfromdate: "Du:",
    pleaseselecttodate: "Au:",
    deductedsitecommission: "Déduction de Commission Exadoctor",
    youbookedanappointment: "Vous avez pris rendez-vous.",
    bookedappointmentandamountinescrow: "Rendez-vous pris et montant en dépôt.",
    appointmentcancelledandrefundedappointmentfee:
      "RDV annulé et frais de RDV remboursés.",
    appointmentcancelledandrefundedfromescrow:
      "RDV annulé et frais de RDV remboursés par séquestre.",
    appointmentcompletedandfeecreditedtowallet:
      "RDV terminé et frais de RDV crédités au portefeuille.",
    paidfordiagnostictest: "Test de diagnostic réglé",
    bookedfordiagnostictest: "Réservé pour le test de diagnostic.",
    youpaidsubscriptionfee: "Vous avez payé vos frais d'abonnement.",
    subscriptionplans: "Abonnements",
    plan: "Plan",
    areyousurewanttocancelsubscription:
      "Voulez-vous vraiment annuler cet abonnement?",
    yourequestedwithdrawamount:
      "Vous avez demandé de retirer le montant disponible.",
    requestedamtcreditedtoaccanddebitfromwallet:
      "Montant de retrait demandé crédité sur votre compte et débité du montant de votre portefeuille disponible.",
    withdrawrequestrejected:
      "La demande de retrait a été rejetée et le montant crédité sur le montant de votre portefeuille disponible.",
    welcomeplansubscriptiontext:
      "Vous avez maintenant accès à un abonnement gratuit. Il expirera le: ######. Après l'expiration du plan, votre profil ne s'affichera pas dans la recherche avant votre renouvellement.",
    noplanssubscribed:
      " Vous n'avez souscrit à aucun plan. Votre profil ne sera pas répertorié dans la recherche avant votre renouvellement.",
    alreadysubscribed:
      "Vous avez déjà souscrit un plan ## PLAN ##. Vous pouvez renouveler une fois après l'expiration du plan",
    paymenterror: "Erreur lors du paiement. Réessayez plus tard.",
    areyousurewanttochangedeliveryoption:
      "Voulez-vous modifier l'option de livraison?",
    paidviaonline: "Paiement en ligne",
    yes: "Oui",
    no: "Non",
    hospitalorclinicname: "Nom de l'établissement de santé",
    pleaseenterhospitalorclinicname:
      "Veuillez entrer le nom de l'établissement de santé",
    hospitalorclinictype: "Type d'établissement de santé",
    pleaseselecthospitalorclinictype:
      "Veuillez sélectionner le type d'établissement de santé",
    qanda: "Q&R",
    findyourperfect: "Prise de RDV en Ligne avec un Professionnel de Santé",
    homelabel: "Hôpital . Clinique . Centre de Diagnostic",
    homesublabel: "",
    menufindadoctor: "Trouver un professionnel de santé",
    menumyaccount: "Mon compte",
    menueditprofile: "Profil",
    menulogin: "S'identifier",
    menusubscription: "Abonnement",
    menugetverified: "Autorisation d'exercice",
    menumyappointment: "Rendez-Vous",
    menumyeducation: "Formation",
    menumylanguage: "Langues",
    menumyspecialty: "Spécialités",
    menumyinsurance: "Assurance",
    menumoneytransferaccount: "Compte",
    menucashwithdrawls: "Retrait d'espèces",
    menutransactions: "Transactions",
    menumyfavorites: "Favoris",
    menumylabtests: "Tests de laboratoire",
    menumedicalrecords: "Dossiers médicaux",
    menulabreports: "Rapports de laboratoire",
    menuaskaquestion: "Vos questions",
    menumedicines: "Médicaments",
    menumybranches: "Etablissements",
    menulanguages: "Langues",
    menutermsandconditions: "Nos conditions",
    menuprivacypolicy: "Confidentialité",
    menuchangepassword: "Mot de passe",
    menudeactivateaccount: "Désactivez mon compte",
    menulogout: "Se déconnecter",
    lblpatient: "Patient",
    lbldoctor: "Médecin",
    prescriptionsupplylbl:
      "Souhaitez-vous que votre prescription soit établie par l'administrateur?",
    lblCountries: {
      Afghanistan: "Afghanistan",
      "South Africa": "Afrique du Sud",
      Albania: "Albanie",
      Algeria: "Algérie",
      Germany: "Allemagne",
      Andorra: "Andorre",
      Angola: "Angola",
      Anguilla: "Anguilla",
      Antarctica: "Antarctique",
      "Antigua and Barbuda": "Antigue-et-Bermudes",
      "Netherlands Antilles": "Antilles néerlandaises",
      "Saudi Arabia": "Arabie saoudite",
      Argentina: "Argentine",
      Armenia: "Arménie",
      Aruba: "Aruba",
      Australia: "Australie",
      Austria: "Autriche",
      Azerbaïdjan: "Azerbaïdjan",
      Bahamas: "Bahamas",
      Bahrain: "Bahrein",
      Bangladesh: "Bangladesh",
      Barbados: "Barbade",
      Belgium: "Belgique",
      Belize: "Belize",
      Benin: "Bénigne",
      Bermuda: "Bermudes",
      Bhutan: "Bhoutan",
      Belarus: "Biélorussie",
      "British Indian Ocean Territory": "BIOT",
      Bolivia: "Bolivie",
      "Bonaire, Saint Eustatius and Saba": "Bonaire-Saint Eustache-Saba",
      "Bosnia and Herzegovina": "Bosnie Herzégovine",
      Botswana: "Botswana",
      Brazil: "Brésil",
      Brunei: "Brunei",
      Bulgaria: "Bulgarie",
      "Burkina Faso": "Burkina Faso",
      Burundi: "Burundi",
      Cambodia: "Cambodge",
      Cameroon: "Cameroun",
      Canada: "Canada",
      "Cape Verde": "Cap-Vert",
      "Central African Republic": "Centrafrique",
      Chile: "Chili",
      China: "Chine",
      Cyprus: "Chypre",
      Colombia: "Colombie",
      Comoros: "Comores",
      "Republic of the Congo": "Congo",
      "North Korea": "Corée du Nord",
      "South Korea": "Corée du Sud",
      "Costa Rica": "Costa Rica",
      "Ivory Coast": "Côte d'Ivoire",
      Croatia: "Croatie",
      Cuba: "Cuba",
      Curacao: "Curaçao",
      Denmark: "Danemark",
      Djibouti: "Djibouti",
      Dominica: "Dominique",
      Egypt: "Egypte",
      "United Arab Emirates": "Émirats Arabes Unis",
      Ecuador: "Équateur",
      Eritrea: "Érythrée",
      Spain: "Espagne",
      Estonia: "Estonie",
      "United States": "États-Unis",
      Ethiopia: "Ethiopie",
      Fiji: "Fidji",
      Finland: "Finlande",
      France: "France",
      Gabon: "Gabon",
      Gambia: "Gambie",
      Georgia: "Géorgie",
      "South Georgia and the South Sandwich Islands":
        "Géorgie du Sud - Îles Sandwich",
      Ghana: "Ghana",
      Gibraltar: "Gibraltar",
      Greece: "Grèce",
      Grenada: "Grenade",
      Greenland: "Groenland",
      Guadeloupe: "Guadeloupe",
      Guam: "Guam",
      Guatemala: "Guatemala",
      Guernsey: "Guernesey",
      Guinea: "Guinée",
      "Equatorial Guinea": "Guinée équatoriale",
      "Guinea-Bissau": "Guinée-Bissau",
      Guyana: "Guyane",
      "French Guiana": "Guyane française",
      Haiti: "Haïti",
      Honduras: "Honduras",
      "Hong Kong": "Hong Kong",
      Hungary: "Hongrie",
      "Bouvet Island": "Île Bouvet",
      "Isle of Man": "Ile de Man",
      "Heard Island and McDonald Islands": "Île Heard - Îles McDonald",
      "Norfolk Island": "île Norfolk",
      "Aland Islands": "Iles Aland",
      "Cayman Islands": "Îles Caïmans",
      "Cocos Islands": "Îles Cocos",
      "Cook Islands": "Îles Cook",
      "Falkland Islands": "îles Falkland",
      "Faroe Islands": "Îles Féroé",
      "Northern Mariana Islands": "Îles Mariannes du Nord",
      "Marshall Islands": "Îles Marshall",
      "United States Minor Outlying Islands":
        "Îles mineures éloignées des États-Unis",
      "Solomon Islands": "Îles Salomon",
      "Turks and Caicos Islands": "Îles Turques et Caïques",
      "U.S. Virgin Islands": "Îles Vierges américaines",
      "British Virgin Islands": "Îles Vierges britanniques",
      India: "Inde",
      Indonesia: "Indonésie",
      Iran: "Iran",
      Iraq: "Iraq",
      Ireland: "Irlande",
      Iceland: "Islande",
      Israel: "Israël",
      Italy: "Italie",
      Jamaica: "Jamaïque",
      Japan: "Japon",
      Jersey: "Jersey",
      Jordan: "Jordan",
      Kazakhstan: "Kazakhstan",
      Kenya: "Kenya",
      Kyrgyzstan: "Kirghizistan",
      Kiribati: "Kiribati",
      Kosovo: "Kosovo",
      Kuwait: "Koweït",
      Laos: "Laos",
      "Christmas Island": "le Christmas",
      Lesotho: "Lesotho",
      Latvia: "Lettonie",
      Lebanon: "Liban",
      Liberia: "Liberia",
      Libya: "Libye",
      Liechtenstein: "Liechtenstein",
      Lithuania: "Lituanie",
      Luxembourg: "Luxembourg",
      Macao: "Macao",
      Macedonia: "Macédoine",
      Madagascar: "Madagascar",
      Malaysia: "Malaisie",
      Malawi: "Malawi",
      Maldives: "Maldives",
      Mali: "Mali",
      Malta: "Malte",
      Morocco: "Maroc",
      Martinique: "Martinique",
      Mauritius: "Maurice",
      Mauritania: "Mauritanie",
      Mayotte: "Mayotte",
      Mexico: "Mexique",
      Micronesia: "Micronésie",
      Moldova: "Moldova",
      Monaco: "Monaco",
      Mongolia: "Mongolie",
      Montenegro: "Monténégro",
      Montserrat: "Montserrat",
      Mozambique: "Mozambique",
      Myanmar: "Myanmar",
      Namibia: "Namibie",
      Nauru: "Nauru",
      Nepal: "Népal",
      Nicaragua: "Nicaragua",
      Niger: "Niger",
      Nigeria: "Nigéria",
      Niue: "Niue",
      Norway: "Norvège",
      "New Caledonia": "Nouvelle-Calédonie",
      "New Zealand": "Nouvelle-Zélande",
      Oman: "Oman",
      Uganda: "Ouganda",
      Uzbekistan: "Ouzbékistan",
      Pakistan: "Pakistan",
      Palau: "Palau",
      "Palestinian Territory": "Palestine",
      Panama: "Panama",
      "Papua New Guinea": "Papouasie-Nelle-Guinée",
      Paraguay: "Paraguay",
      Netherlands: "Pays-Bas",
      Peru: "Pérou",
      Philippines: "Philippines",
      Pitcairn: "Pitcairn",
      Poland: "Pologne",
      "French Polynesia": "Polynésie française",
      "Puerto Rico": "Porto Rico",
      Portugal: "Portugal",
      Qatar: "Qatar",
      "Democratic Republic of the Congo": "RDC Congo",
      Reunion: "Réunion",
      Romania: "Roumanie",
      "United Kingdom": "Royaume-Uni",
      Russia: "Russie",
      Rwanda: "Rwanda",
      "Western Sahara": "Sahara occidental",
      "Saint Barthelemy": "Saint Barthelemy",
      "Saint Martin": "Saint Martin",
      "Saint Pierre and Miquelon": "Saint Pierre et Miquelon",
      "Dominican Republic": "Saint-Domingue",
      "Saint Helena": "Sainte-Hélène",
      "Saint Lucia": "Sainte-Lucie",
      "Saint Kitts and Nevis": "Saint-Kitts-et-Nevis",
      "San Marino": "Saint-Marin",
      "Sint Maarten": "Saint-Martin",
      "Saint Vincent and the Grenadines": "Saint-Vincent SVG",
      "El Salvador": "Salvador",
      Samoa: "Samoa",
      "American Samoa": "Samoa américaines",
      "Sao Tome and Principe": "Sao Tomé et Principe",
      Senegal: "Sénégal",
      Serbia: "Serbie",
      "Serbia and Montenegro": "Serbie et Monténégro",
      Seychelles: "Seychelles",
      "Sierra Leone": "Sierra Leone",
      Singapore: "Singapour",
      Slovakia: "Slovaquie",
      Slovenia: "Slovénie",
      Somalia: "Somalie",
      Sudan: "Soudan",
      "South Sudan": "Soudan du Sud",
      "Sri Lanka": "Sri Lanka",
      Sweden: "Suède",
      Switzerland: "Suisse",
      Suriname: "Suriname",
      "Svalbard and Jan Mayen": "Svalbard et Jan Mayen",
      Swaziland: "Swaziland",
      Syria: "Syrie",
      "French Southern Territories": "TAAF",
      Tajikistan: "Tadjikistan",
      Taiwan: "Taiwan",
      Tanzania: "Tanzanie",
      Chad: "Tchad",
      "Czech Republic": "Tchéquie",
      Thailand: "Thaïlande",
      "East Timor": "Timor oriental",
      Togo: "Togo",
      Tokelau: "Tokelau",
      Tonga: "Tonga",
      "Trinidad and Tobago": "Trinité-et-Tobago",
      Tunisia: "Tunisie",
      Turkmenistan: "Turkménistan",
      Turkey: "Turquie",
      Tuvalu: "Tuvalu",
      Ukraine: "Ukraine",
      Uruguay: "Uruguay",
      Vanuatu: "Vanuatu",
      Vatican: "Vatican",
      Venezuela: "Vénézuela",
      Vietnam: "Vietnam",
      "Wallis and Futuna": "Wallis et Futuna",
      Yemen: "Yémen",
      Zambia: "Zambie",
      Zimbabwe: "Zimbabwe",
    },
    weekdays: {
      0: "Dim",
      1: "Lun",
      2: "Mar",
      3: "Mer",
      4: "Jeu",
      5: "Ven",
      6: "Sam",
    },
    lblappointmentstatus: {
      1: "En attente de confirmation",
      2: "Confirmé",
      3: "Terminé",
      4: "Annulé",
      5: "Rejeté",
      6: "Expiré",
      7: "En cours",
      8: "Enquête",
      9: "Pré-approuvé",
      10: "Paiement en attente",
      11: "Annulé par l'administrateur",
    },
    lblinsurances: {
      1: "Axa",
      2: "Allianz",
      3: "Groupama",
      4: "La Mondiale",
      5: "Macif",
      6: "MMA",
      7: "MAIF",
      8: "GMF",
    },
    lblspecialities: {
      1: "Allergologue",
      2: "Anesthésiste",
      3: "Biologiste",
      4: "Cardiologue",
      5: "Chirurgien vasculaire",
      6: "Chirurgien",
      7: "Dentiste",
      8: "Dermatologue",
      9: "Oto-Rhino-Laryngologue",
      10: "Endocrinologue",
      11: "Ophtalmologue",
      12: "Physiatre",
      13: "Gastro-entérologue",
      14: "Médecin généraliste",
      15: "Gériatre",
      16: "Gynécologue-Obstétricien",
      18: "Chirurgien de la main",
      19: "Interniste",
      21: "Néphrologue",
      22: "Neurologue",
      23: "Psychiatre",
      24: "Ergothérapeute",
      25: "Neurochirurgien",
      26: "Spécialiste en médecine nucléaire",
      28: "Infirmière",
      29: "Sage-femme",
      30: "Orthodontiste",
      31: "Orthopédiste",
      32: "Ostéopathe D.O.",
      33: "Pédopsychiatre",
      34: "Pédiatre",
      35: "Physiothérapeute",
      36: "Chirurgien plastique",
      37: "Psychiatre",
      38: "Pneumologue",
      39: "Radiologue",
      40: "Rhumatologue",
      41: "Sophrologue",
      42: "Spécialiste en médecine du sport",
      43: "Stomatologue",
      44: "Audioprothésiste",
      45: "Urologue",
      46: "Chirurgien vasculaire",
      47: "Phlébologue",
      52: "Pharmacien",
      54: "Pédicure-Podologue",
      55: "Podo-orthésiste ",
      56: "Psychologue",
      57: "Echographiste",
      58: "Laboratoire médical",
      60: "Spécialiste en Coaching",
      61: "Coach sportif",
      62: "Masseur-kinésithérapeute",
      63: "Réflexologue",
      65: "IRM",
      66: "Scanner",
      68: "Consultation",
      69: "Acupuncteur",
      70: "Chirurgien esthétique",
    },
    deactivateconfirmation:
      "Êtes-vous sûr de vouloir désactiver votre compte ?",
    deactivatesuccess: "Votre compte a été désactivé avec succès",
    deactivatetryagain: "Quelque chose a mal tourné, veuillez réessayer",
  },
});
module.exports = Strings;
